/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferenciasRouteImport } from './routes/transferencias'
import { Route as RetornosRouteImport } from './routes/retornos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PerdidosRouteImport } from './routes/perdidos'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as OperacaoInstagramRouteImport } from './routes/operacao-instagram'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LancamentoRouteImport } from './routes/lancamento'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as AutomacoesRouteImport } from './routes/automacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const TransferenciasRoute = TransferenciasRouteImport.update({
  id: '/transferencias',
  path: '/transferencias',
  getParentRoute: () => rootRouteImport,
} as any)
const RetornosRoute = RetornosRouteImport.update({
  id: '/retornos',
  path: '/retornos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PerdidosRoute = PerdidosRouteImport.update({
  id: '/perdidos',
  path: '/perdidos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacaoInstagramRoute = OperacaoInstagramRouteImport.update({
  id: '/operacao-instagram',
  path: '/operacao-instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentoRoute = LancamentoRouteImport.update({
  id: '/lancamento',
  path: '/lancamento',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomacoesRoute = AutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/inbox': typeof InboxRoute
  '/lancamento': typeof LancamentoRoute
  '/logs': typeof LogsRoute
  '/metricas': typeof MetricasRoute
  '/operacao-instagram': typeof OperacaoInstagramRoute
  '/orcamentos': typeof OrcamentosRoute
  '/perdidos': typeof PerdidosRoute
  '/pipeline': typeof PipelineRoute
  '/relatorios': typeof RelatoriosRoute
  '/retornos': typeof RetornosRoute
  '/transferencias': typeof TransferenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/inbox': typeof InboxRoute
  '/lancamento': typeof LancamentoRoute
  '/logs': typeof LogsRoute
  '/metricas': typeof MetricasRoute
  '/operacao-instagram': typeof OperacaoInstagramRoute
  '/orcamentos': typeof OrcamentosRoute
  '/perdidos': typeof PerdidosRoute
  '/pipeline': typeof PipelineRoute
  '/relatorios': typeof RelatoriosRoute
  '/retornos': typeof RetornosRoute
  '/transferencias': typeof TransferenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/automacoes': typeof AutomacoesRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/inbox': typeof InboxRoute
  '/lancamento': typeof LancamentoRoute
  '/logs': typeof LogsRoute
  '/metricas': typeof MetricasRoute
  '/operacao-instagram': typeof OperacaoInstagramRoute
  '/orcamentos': typeof OrcamentosRoute
  '/perdidos': typeof PerdidosRoute
  '/pipeline': typeof PipelineRoute
  '/relatorios': typeof RelatoriosRoute
  '/retornos': typeof RetornosRoute
  '/transferencias': typeof TransferenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/automacoes'
    | '/contatos'
    | '/conversas'
    | '/inbox'
    | '/lancamento'
    | '/logs'
    | '/metricas'
    | '/operacao-instagram'
    | '/orcamentos'
    | '/perdidos'
    | '/pipeline'
    | '/relatorios'
    | '/retornos'
    | '/transferencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/automacoes'
    | '/contatos'
    | '/conversas'
    | '/inbox'
    | '/lancamento'
    | '/logs'
    | '/metricas'
    | '/operacao-instagram'
    | '/orcamentos'
    | '/perdidos'
    | '/pipeline'
    | '/relatorios'
    | '/retornos'
    | '/transferencias'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/automacoes'
    | '/contatos'
    | '/conversas'
    | '/inbox'
    | '/lancamento'
    | '/logs'
    | '/metricas'
    | '/operacao-instagram'
    | '/orcamentos'
    | '/perdidos'
    | '/pipeline'
    | '/relatorios'
    | '/retornos'
    | '/transferencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  AutomacoesRoute: typeof AutomacoesRoute
  ContatosRoute: typeof ContatosRoute
  ConversasRoute: typeof ConversasRoute
  InboxRoute: typeof InboxRoute
  LancamentoRoute: typeof LancamentoRoute
  LogsRoute: typeof LogsRoute
  MetricasRoute: typeof MetricasRoute
  OperacaoInstagramRoute: typeof OperacaoInstagramRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PerdidosRoute: typeof PerdidosRoute
  PipelineRoute: typeof PipelineRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RetornosRoute: typeof RetornosRoute
  TransferenciasRoute: typeof TransferenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transferencias': {
      id: '/transferencias'
      path: '/transferencias'
      fullPath: '/transferencias'
      preLoaderRoute: typeof TransferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retornos': {
      id: '/retornos'
      path: '/retornos'
      fullPath: '/retornos'
      preLoaderRoute: typeof RetornosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perdidos': {
      id: '/perdidos'
      path: '/perdidos'
      fullPath: '/perdidos'
      preLoaderRoute: typeof PerdidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacao-instagram': {
      id: '/operacao-instagram'
      path: '/operacao-instagram'
      fullPath: '/operacao-instagram'
      preLoaderRoute: typeof OperacaoInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamento': {
      id: '/lancamento'
      path: '/lancamento'
      fullPath: '/lancamento'
      preLoaderRoute: typeof LancamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automacoes': {
      id: '/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AutomacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  AutomacoesRoute: AutomacoesRoute,
  ContatosRoute: ContatosRoute,
  ConversasRoute: ConversasRoute,
  InboxRoute: InboxRoute,
  LancamentoRoute: LancamentoRoute,
  LogsRoute: LogsRoute,
  MetricasRoute: MetricasRoute,
  OperacaoInstagramRoute: OperacaoInstagramRoute,
  OrcamentosRoute: OrcamentosRoute,
  PerdidosRoute: PerdidosRoute,
  PipelineRoute: PipelineRoute,
  RelatoriosRoute: RelatoriosRoute,
  RetornosRoute: RetornosRoute,
  TransferenciasRoute: TransferenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
